### ISSUE TITLE
[🐞] useVisibleTask$ called twice

### ISSUE THREAD

**Issue by gioboa** [dannyfranca/qwik-router#6]
### Which component is affected?

Qwik Runtime

### Describe the bug

I cloned your starter 
`git clone https://github.com/dannyfranca/qwik-router.git`
and I added `useVisibleTask$` in the Route1 component [here](https://github.com/dannyfranca/qwik-router/blob/f4820948ef619f464c630fd7bc7797ae9d9162e3/packages/qwik-router/src/root.tsx#L12) 
```
useVisibleTask$(() => {
  console.log('useVisibleTask');
});
```
and the `useVisibleTask$` called twice 

### Reproduction

-

### Steps to reproduce

-

### Additional Information

to avoid this problem I can create my own useVisibleTask$ wrapper

**Comment by dannyfranca** [comment]
Thanks for the feedback, @gioboa. I have been busy, I'll look into it this week.

**Comment by dannyfranca** [comment]
@gioboa, in this case, this is the expected behaviour. Each Router component has its context and its parameters. If you notice, the Route1 component belongs to the two routers in the example, which is why the `useVisibleTask$` is executed twice. Executing one, would overwrite the other Router component's behaviour.

Given that, tell me if you would expect a different behaviour and why.

**Comment by gioboa** [comment]
I see, in the meantime I solve my personal problem with a ternary `{ route === 'A' ? <CmpA /> : <CmpB /> }`
I will give another try to the lib. Thanks for your work 👍
